### PR TITLE
Improve Goals by integrating clarifications from @tidoust

### PR DESCRIPTION
**Pull request by anssiko**
This is an attempt to improve the current [Goals](https://webscreens.github.io/cg-charter/#goals) section by integrating [clarifications](https://webscreens.github.io/cg-charter/#goals) from @tidoust. 

See the [Goals with these changes baked in](http://rawgit.com/anssiko/cg-charter/goals/index.html#goals).

Everyone happy with these high level goals?

Cc @wcarr @tidoust @mfoltzgoogle @louaybassbouss @schien @karim76

### CODE REVIEW

**Comment by louaybassbouss** [comment]
+1

**Comment by tidoust** [comment]
Obviously, I'm fine with these high-level goals ;)

One comment on "proposals worked on in the CG will be considered for migration to an appropriate W3C Working Group": although it will depend on the actual contents of these proposals, W3C is likely not going to be the right place for the standardization of protocols. IETF seems more appropriate.

I suggest to extend to "an appropriate W3C or IETF Working Group".

**Comment by anssiko** [comment]
@tidoust amended as proposed.

**Comment by anssiko** [comment]
I'll merge this -- let's revisit the Goals section after we have an agreement on the list of concrete Deliverables.

**Pull request merged**
